# Generated by Django 4.1.9 on 2023-05-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5, unique=True, verbose_name='Código')),
                ('codigo', models.CharField(max_length=50, verbose_name='Nombre del Organismo')),
                ('sigla', models.CharField(max_length=13, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'db_table': 'organismo',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Provincia')),
                ('codigo', models.CharField(max_length=2, verbose_name='Código')),
                ('sigla', models.CharField(max_length=3, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Osde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del OSDE')),
                ('sigla', models.CharField(max_length=13, verbose_name='Sigla')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.organismo', verbose_name='Organismo')),
            ],
            options={
                'verbose_name': 'OSDE',
                'verbose_name_plural': 'OSDE',
                'db_table': 'osde',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Municipio')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('entity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('reup_code', models.CharField(max_length=120, null=True, verbose_name='Código REEUP')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.municipio', verbose_name='Municipio')),
                ('osde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.osde', verbose_name='Osde')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['nombre'],
            },
        ),
    ]
