# Generated by Django 4.1.9 on 2023-05-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_organismo_codigo_alter_organismo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='codigo',
            field=models.CharField(max_length=5, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
