# Generated by Django 4.1.9 on 2023-05-27 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_organismo_codigo_alter_organismo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría Equipo',
                'verbose_name_plural': 'Categorías Equipos',
                'db_table': 'categoria_equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría Insumo',
                'verbose_name_plural': 'Categorías Insumos',
                'db_table': 'categoria_insumo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría Parte',
                'verbose_name_plural': 'Categorías Partes',
                'db_table': 'categoria_parte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría Pieza',
                'verbose_name_plural': 'Categorías Piezas',
                'db_table': 'categoria_pieza',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Sin asignar', 'Sin asignar'), ('Reparación', 'Reparación')], max_length=11)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Equipo/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.categoriaequipo', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.categoriainsumo', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'insumo',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.BooleanField(default=False, verbose_name='Equipo')),
                ('parte', models.BooleanField(default=False, verbose_name='Parte')),
                ('pieza', models.BooleanField(default=False, verbose_name='Pieza')),
                ('insumo', models.BooleanField(default=False, verbose_name='Insumo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca Modelo',
                'verbose_name_plural': 'Marcas Modelos',
                'db_table': 'marca_modelo',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Modelo')),
                ('marca', models.ManyToManyField(blank=True, through='dashboards.MarcaModelo', to='dashboards.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Parte/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.categoriaparte', verbose_name='Categoría')),
                ('insumo', models.ManyToManyField(blank=True, to='dashboards.insumo', verbose_name='Insumo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboards.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
                'db_table': 'parte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Pieza/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.categoriapieza', verbose_name='Categoria Pieza')),
                ('insumo', models.ManyToManyField(blank=True, to='dashboards.insumo', verbose_name='Insumo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.marca', verbose_name='Marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboards.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
                'db_table': 'pieza',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'propiedad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.equipo', verbose_name='Equipo')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad Equipo',
                'verbose_name_plural': 'Propiedades Equipos',
                'db_table': 'propiedad_equipo',
                'unique_together': {('equipo', 'propiedad')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.insumo', verbose_name='Insumo')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad Insumo',
                'verbose_name_plural': 'Propiedades Insumos',
                'db_table': 'propiedad_insumo',
                'unique_together': {('insumo', 'propiedad')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.parte', verbose_name='Parte')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad Parte',
                'verbose_name_plural': 'Propiedades Partes',
                'db_table': 'propiedad_parte',
                'unique_together': {('propiedad', 'parte')},
            },
        ),
        migrations.CreateModel(
            name='PropiedadPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.pieza', verbose_name='Pieza')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Propiedad Pieza',
                'verbose_name_plural': 'Propiedades Piezas',
                'db_table': 'propiedad_pieza',
                'unique_together': {('propiedad', 'pieza')},
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='entity_type',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.AddField(
            model_name='pieza',
            name='propiedades',
            field=models.ManyToManyField(blank=True, through='dashboards.PropiedadPieza', to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='parte',
            name='piezas',
            field=models.ManyToManyField(blank=True, to='dashboards.pieza', verbose_name='Pieza'),
        ),
        migrations.AddField(
            model_name='parte',
            name='propiedades',
            field=models.ManyToManyField(blank=True, through='dashboards.PropiedadParte', to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='marcamodelo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='propiedades',
            field=models.ManyToManyField(blank=True, through='dashboards.PropiedadInsumo', to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboards.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partes',
            field=models.ManyToManyField(blank=True, to='dashboards.parte', verbose_name='Parte'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='propiedades',
            field=models.ManyToManyField(blank=True, through='dashboards.PropiedadEquipo', to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='categoriapieza',
            name='propiedad',
            field=models.ManyToManyField(blank=True, to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='categoriaparte',
            name='propiedad',
            field=models.ManyToManyField(blank=True, to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='propiedad',
            field=models.ManyToManyField(blank=True, to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
        migrations.AddField(
            model_name='categoriaequipo',
            name='propiedad',
            field=models.ManyToManyField(blank=True, to='dashboards.propiedad', verbose_name='Propiedad'),
        ),
    ]
