# Generated by Django 4.1.9 on 2023-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_equipo_chapa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propiedadequipo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='propiedadparte',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='propiedadpieza',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='chapa',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Chapa'),
        ),
    ]
