# Generated by Django 4.1.9 on 2023-06-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0008_provincia_alter_empresa_osde_empresa_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
