# Generated by Django 4.1.9 on 2023-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_alter_categoriaequipo_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
