# Generated by Django 4.1.9 on 2023-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0014_alter_organismo_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
