# Generated by Django 4.1.9 on 2023-06-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_alter_categoriaequipo_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaequipo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='CategoriaEquipo/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Reparación', 'Reparación'), ('Venta', 'Venta')], max_length=11),
        ),
    ]
